/**
 * Turning a day-by-model table into the handful of numbers the page states.
 *
 * Away from the drawing because every one of these is a definition, not a calculation, and the
 * definitions are where this goes wrong: a streak that counts today as a break when the day is
 * young, a range that is off by one day at the far end, a "most used" that ranks by number of
 * replies when the question is about tokens. None of that is visible in a screenshot.
 */

import type { UsageBucket, UsageDay, UsageScan } from "../../../electron/usage-scan.ts";

export type Range = 7 | 30 | 0;

export interface Totals {
	input: number;
	output: number;
	cacheRead: number;
	cacheWrite: number;
	cost: number;
	/** Everything the model read and wrote — what 「tokens 用量」 means. */
	tokens: number;
	replies: number;
	messages: number;
	/** Conversation-days: one conversation active on three days counts three times. */
	sessionDays: number;
	activeDays: number;
}

export interface ModelUse {
	key: string;
	provider: string;
	model: string;
	tokens: number;
	cost: number;
	replies: number;
	/** 0–1 of the range's tokens, for the bar beside it. */
	share: number;
}

/**
 * What to call a provider the logs only know by id.
 *
 * A reply records the provider it was answered by as an id — `relay`, or an autogenerated
 * `provider-mszq0hpb` for one added from the settings page — and that is not a name anybody
 * recognises on a page about where their money went. The configured name is used when the provider
 * still exists; the id survives as the fallback, because a provider that has since been deleted
 * still spent what it spent and the row has to say something.
 */
export function providerLabel(providers: { id: string; name: string }[] | undefined, id: string): string {
	return providers?.find((each) => each.id === id)?.name ?? id;
}

/** Local date key. Same rule as the scanner: a turn at 23:00 belongs to the day you had it. */
export function dayKey(date: Date): string {
	const month = `${date.getMonth() + 1}`.padStart(2, "0");
	const day = `${date.getDate()}`.padStart(2, "0");
	return `${date.getFullYear()}-${month}-${day}`;
}

/**
 * The first day of a range, inclusive.
 *
 * 「最近 7 天」 counts today as one of the seven, which is what everyone means by it and what makes
 * the number comparable to the seven days before it.
 */
export function rangeStart(range: Range, now: Date): string | null {
	if (range === 0) return null;
	const start = new Date(now.getFullYear(), now.getMonth(), now.getDate());
	start.setDate(start.getDate() - (range - 1));
	return dayKey(start);
}

export function withinRange<T extends { day: string }>(rows: T[], from: string | null): T[] {
	return from === null ? rows : rows.filter((row) => row.day >= from);
}

export function totalsFor(buckets: UsageBucket[], days: UsageDay[]): Totals {
	const totals: Totals = {
		input: 0,
		output: 0,
		cacheRead: 0,
		cacheWrite: 0,
		cost: 0,
		tokens: 0,
		replies: 0,
		messages: 0,
		sessionDays: 0,
		activeDays: 0,
	};
	for (const bucket of buckets) {
		totals.input += bucket.input;
		totals.output += bucket.output;
		totals.cacheRead += bucket.cacheRead;
		totals.cacheWrite += bucket.cacheWrite;
		totals.cost += bucket.cost;
		totals.replies += bucket.replies;
		/*
		 * Cache reads are tokens the model read, and they are most of the bill on a long
		 * conversation — leaving them out would report a fraction of the real traffic and make
		 * the cache look free rather than cheap.
		 */
		totals.tokens += bucket.input + bucket.output + bucket.cacheRead + bucket.cacheWrite;
	}
	for (const day of days) {
		totals.messages += day.messages;
		totals.sessionDays += day.sessions;
		if (day.messages > 0) totals.activeDays += 1;
	}
	return totals;
}

/**
 * Consecutive days ending today, or ending yesterday.
 *
 * Yesterday counts as the end because a streak should not be reported as broken at 09:00 on a day
 * whose work has not happened yet — that reads as having lost something you still have. Two days
 * of silence is a break either way.
 */
export function currentStreak(days: UsageDay[], now: Date): number {
	const active = new Set(days.filter((day) => day.messages > 0).map((day) => day.day));
	const cursor = new Date(now.getFullYear(), now.getMonth(), now.getDate());
	if (!active.has(dayKey(cursor))) {
		cursor.setDate(cursor.getDate() - 1);
		if (!active.has(dayKey(cursor))) return 0;
	}
	let streak = 0;
	while (active.has(dayKey(cursor))) {
		streak += 1;
		cursor.setDate(cursor.getDate() - 1);
	}
	return streak;
}

/** Models by tokens, heaviest first. Ranked by tokens because that is what is being paid for. */
export function modelRanking(buckets: UsageBucket[]): ModelUse[] {
	const byKey = new Map<string, ModelUse>();
	for (const bucket of buckets) {
		const tokens = bucket.input + bucket.output + bucket.cacheRead + bucket.cacheWrite;
		const seen = byKey.get(bucket.key);
		if (seen) {
			seen.tokens += tokens;
			seen.cost += bucket.cost;
			seen.replies += bucket.replies;
			continue;
		}
		byKey.set(bucket.key, {
			key: bucket.key,
			provider: bucket.provider,
			model: bucket.model,
			tokens,
			cost: bucket.cost,
			replies: bucket.replies,
			share: 0,
		});
	}
	const ranked = [...byKey.values()].sort((a, b) => b.tokens - a.tokens);
	const total = ranked.reduce((sum, each) => sum + each.tokens, 0);
	for (const each of ranked) each.share = total > 0 ? each.tokens / total : 0;
	return ranked;
}

/**
 * One entry per day in the range, including the empty ones.
 *
 * Gaps have to be drawn, not skipped: a bar chart that only plots the days something happened
 * compresses a quiet week into nothing and reports a burst of work as steady.
 */
export function dailySeries(buckets: UsageBucket[], range: Range, now: Date, earliest?: string): { day: string; tokens: number; cost: number }[] {
	const byDay = new Map<string, { tokens: number; cost: number }>();
	for (const bucket of buckets) {
		const seen = byDay.get(bucket.day) ?? { tokens: 0, cost: 0 };
		seen.tokens += bucket.input + bucket.output + bucket.cacheRead + bucket.cacheWrite;
		seen.cost += bucket.cost;
		byDay.set(bucket.day, seen);
	}

	const days: { day: string; tokens: number; cost: number }[] = [];
	const end = new Date(now.getFullYear(), now.getMonth(), now.getDate());
	const start = new Date(end);
	if (range === 0) {
		// 「全部」 runs from the first day anything happened, so the axis is the history itself.
		const first = earliest ?? [...byDay.keys()].sort()[0];
		if (!first) return [];
		const [y, m, d] = first.split("-").map(Number);
		start.setFullYear(y, m - 1, d);
	} else {
		start.setDate(start.getDate() - (range - 1));
	}

	/*
	 * Counted in days rather than walked with a mutating cursor.
	 *
	 * `new Date(y, m, d + n)` normalises across month ends and daylight saving on its own, where
	 * adding 86400000ms twice a year lands on the same calendar day or skips one.
	 */
	const span = Math.round((end.getTime() - start.getTime()) / 86_400_000);
	for (let offset = 0; offset <= span; offset++) {
		const cursor = new Date(start.getFullYear(), start.getMonth(), start.getDate() + offset);
		const key = dayKey(cursor);
		const found = byDay.get(key);
		days.push({ day: key, tokens: found?.tokens ?? 0, cost: found?.cost ?? 0 });
	}
	return days;
}

/**
 * The two halves of a day joined up: how much was said, and what it cost.
 *
 * The scan keeps them apart because they are counted differently — messages come from both sides
 * of every conversation, tokens only from the replies — and the heatmap needs them together, keyed
 * by the same day.
 */
export function dayTotals(scan: UsageScan): { day: string; sessions: number; messages: number; tokens: number; cost: number }[] {
	const byDay = new Map<string, { day: string; sessions: number; messages: number; tokens: number; cost: number }>();
	for (const day of scan.days) {
		byDay.set(day.day, { day: day.day, sessions: day.sessions, messages: day.messages, tokens: 0, cost: 0 });
	}
	for (const bucket of scan.buckets) {
		const seen = byDay.get(bucket.day) ?? { day: bucket.day, sessions: 0, messages: 0, tokens: 0, cost: 0 };
		seen.tokens += bucket.input + bucket.output + bucket.cacheRead + bucket.cacheWrite;
		seen.cost += bucket.cost;
		byDay.set(bucket.day, seen);
	}
	return [...byDay.values()].sort((a, b) => a.day.localeCompare(b.day));
}

/** Everything the page needs for one range, from one scan. */
export function summarise(scan: UsageScan, range: Range, now: Date) {
	const from = rangeStart(range, now);
	const buckets = withinRange(scan.buckets, from);
	const days = withinRange(scan.days, from);
	return {
		totals: totalsFor(buckets, days),
		models: modelRanking(buckets),
		series: dailySeries(buckets, range, now, scan.days[0]?.day),
		streak: currentStreak(scan.days, now),
	};
}
