#!/usr/bin/env bash
#
# Put the Android release key where Gradle will find it.
#
# Why this is not optional for a release. `expo prebuild` generates `android/app/build.gradle` from
# React Native's template, and that template signs the *release* build type with the *debug*
# keystore:
#
#     signingConfigs { debug { storeFile file('debug.keystore') storePassword 'android' … } }
#     buildTypes { release { … signingConfig signingConfigs.debug } }
#
# So `assembleRelease` on a bare checkout produces an APK that installs — and that is the trap.
# Android ties an app's identity to its signing certificate: an APK signed with the template's
# debug key cannot be replaced by a properly signed one. The user has to uninstall first, which
# takes their pairing with it. And that debug key is public — it ships inside the template — so
# anybody can build an "update" the phone will accept. Neither is something a release can take
# back, which is why `REQUIRE_SIGNING` works exactly as it does for the macOS certificate:
#
#   true   a missing keystore is fatal, before anything is built.
#   false  a missing keystore is a warning, and the rehearsal still rehearses the packaging —
#          the APK it produces is named `-debugkey` so nobody mistakes it for a release.
#
# The secret is read here rather than in the step's `if:`, because the `secrets` context is not
# available to a step condition — see the same note in `prepare-signing.sh`.
#
# Runnable outside CI: `RUNNER_TEMP` and `GITHUB_ENV` both fall back, so this can be driven by hand
# to check that a keystore and its passwords actually open.

set -euo pipefail

RUNNER_TEMP="${RUNNER_TEMP:-${TMPDIR:-/tmp}}"
# The generated project's own properties file, not the one in `$HOME/.gradle`.
#
# Both are read by Gradle and only one is thrown away: this directory is regenerated by the next
# `prebuild` and deleted with the runner, while the home one outlives every other step and job on
# the machine. A password belongs in the shorter-lived of the two.
GRADLE_PROPERTIES="${LYRA_GRADLE_PROPERTIES:-packages/mobile/android/gradle.properties}"

# `LYRA_ANDROID_SIGNED` is how the workflow names the artifact. Written to the environment file
# when there is one, and printed otherwise so a hand run says what it decided.
announce() {
	if [ -n "${GITHUB_ENV:-}" ]; then echo "$1" >> "$GITHUB_ENV"; else echo "$1"; fi
}

if [ -z "${ANDROID_KEYSTORE_BASE64:-}" ]; then
	if [ "${REQUIRE_SIGNING:-false}" = "true" ]; then
		echo "::error::ANDROID_KEYSTORE_BASE64 is not set. Releasing an APK signed with React Native's public debug key would mean every later, properly signed release cannot update it — the user has to uninstall — and anybody holding that key can build an update the phone accepts. Create the keystore with packages/mobile/scripts/make-release-keystore.sh; it prints the four secrets to set."
		exit 1
	fi
	echo "::warning::ANDROID_KEYSTORE_BASE64 is not set — this APK will carry React Native's debug key and is not installable as an update"
	announce "LYRA_ANDROID_SIGNED=false"
	exit 0
fi

for name in ANDROID_KEYSTORE_PASSWORD ANDROID_KEY_ALIAS ANDROID_KEY_PASSWORD; do
	if [ -z "${!name:-}" ]; then
		echo "::error::$name is not set, but ANDROID_KEYSTORE_BASE64 is. All four go together; make-release-keystore.sh prints them."
		exit 1
	fi
done

KEYSTORE="$RUNNER_TEMP/lyra-release.keystore"
echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$KEYSTORE"

# Prove the key opens before Gradle spends twenty minutes finding out.
#
# A wrong password fails at the very end of the build, in the packaging task, with a stack trace
# about a keystore rather than about a secret. Asking keytool first costs a second and names the
# problem.
if ! keytool -list -keystore "$KEYSTORE" -storepass "$ANDROID_KEYSTORE_PASSWORD" -alias "$ANDROID_KEY_ALIAS" > /dev/null 2>&1; then
	echo "::error::The keystore decoded, but it does not open with ANDROID_KEYSTORE_PASSWORD, or it holds no key called '$ANDROID_KEY_ALIAS'."
	exit 1
fi

# `android.injected.signing.*`, the properties AGP reads instead of whatever the template says.
#
# Chosen over editing the generated `build.gradle`: the file is regenerated by every `prebuild`, so
# a patch to it is a patch that has to be reapplied and can silently stop matching. These four
# properties override the build type's own `signingConfig` with no edit at all.
#
# They go in `gradle.properties` rather than on the command line so the passwords are not in the
# process list of a runner that also runs Gradle daemons and test processes.
if [ ! -f "$GRADLE_PROPERTIES" ]; then
	echo "::error::$GRADLE_PROPERTIES does not exist — run \`expo prebuild --platform android\` before this."
	exit 1
fi
{
	# A newline of our own first: the generated file ends without one, so the first property
	# appended lands on the end of `expo.inlineModules.watchedDirectories=[]` and neither line is
	# read. Found by running this and diffing the file, which is the only way it shows — Gradle
	# does not complain about a property it never saw.
	echo ""
	echo "android.injected.signing.store.file=$KEYSTORE"
	echo "android.injected.signing.store.password=$ANDROID_KEYSTORE_PASSWORD"
	echo "android.injected.signing.key.alias=$ANDROID_KEY_ALIAS"
	echo "android.injected.signing.key.password=$ANDROID_KEY_PASSWORD"
} >> "$GRADLE_PROPERTIES"

announce "LYRA_ANDROID_SIGNED=true"
echo "Release key ready: $(keytool -list -keystore "$KEYSTORE" -storepass "$ANDROID_KEYSTORE_PASSWORD" -alias "$ANDROID_KEY_ALIAS" | tail -1)"
