import type { MessageCatalog } from "./zh-CN.ts";

export const ja = {
	"common.cancel": "キャンセル", "common.confirm": "確認", "common.delete": "削除", "common.hide": "非表示", "common.loading": "開いています", "common.save": "保存", "common.show": "表示",
	"app.backWorkspace": "ワークスペースに戻る", "app.guide": "ガイド", "app.hideSettingsNavigation": "設定ナビゲーションを隠す {shortcut}", "app.mainProcessError": "メインプロセスのエラー", "app.panel": "パネル", "app.plugins": "プラグイン", "app.pullRequests": "プルリクエスト", "app.scheduledTasks": "予約タスク", "app.settingsNavigation": "設定ナビゲーション", "app.showSettingsNavigation": "設定ナビゲーションを表示 {shortcut}", "app.sidebar": "サイドバー",
	"language.title": "表示言語", "language.detail": "Lyra のメニュー、設定、操作ヒントの言語を変更します。会話、コード、ターミナル出力は原文のまま表示します。", "language.system": "システム設定に従う", "language.systemDetected": "現在のシステム言語", "language.zh-CN": "简体中文", "language.zh-TW": "繁體中文", "language.en": "English", "language.fr": "Français", "language.ru": "Русский", "language.ko": "한국어", "language.ja": "日本語",
	"settings.group.basic": "基本設定", "settings.group.agent": "エージェント機能", "settings.group.data": "データと使用状況", "settings.group.vcs": "コードとバージョン管理", "settings.group.about": "情報とアーカイブ", "settings.general": "一般", "settings.appearance": "外観", "settings.formatting": "コード整形", "settings.personalization": "パーソナライズ", "settings.models": "モデル", "settings.forges": "コードホスティング", "settings.screenshot": "スクリーンショット", "settings.browser": "ブラウザ", "settings.extensions": "プラグイン", "settings.agents": "サブエージェント", "settings.delegation": "サブエージェント委任", "settings.commands": "コマンド", "settings.hooks": "フック", "settings.search": "ウェブ検索", "settings.access": "アクセス権", "settings.index": "インデックス", "settings.sync": "モバイル同期", "settings.usage": "使用状況", "settings.worktrees": "Worktrees", "settings.about": "Lyra について", "settings.archived": "アーカイブ済みの会話",
	"general.permissions": "権限", "general.defaultPermission": "標準のアクセス権", "general.defaultPermissionDetail": "Lyra は現在のワークスペース内のファイルを常に読み書きできます。必要に応じて追加のアクセス権を求めます。", "general.alwaysEnabled": "常に有効", "general.autoReview": "自動審査", "general.autoReviewDetail": "git status、ls、grep などの読み取り専用コマンドは自動で許可します。書き込みと不明なコマンドには引き続き承認が必要です。", "general.fullAccess": "フルアクセス", "general.fullAccessDetail": "Lyra が承認なしでファイルを編集し、コマンドを実行してネットワークへアクセスできるようになります。データ損失や意図しない操作の危険が大きくなります。", "general.section": "一般", "general.fileTarget": "標準のファイル起動先", "general.fileTargetDetail": "ファイルパスをクリックしたときに使うアプリを選びます", "general.thinking": "標準の推論強度", "general.thinkingDetail": "新しい会話の推論予算です。会話ごとに入力欄の右側から変更できます。", "general.retry": "リクエストの再試行", "general.retryDetail": "ネットワークエラー後にモデルへリクエストする回数です。最初の試行も含みます。出力が始まった回答は再試行しません。", "general.bottomPanel": "下部パネル", "general.bottomPanelDetail": "会話の下に使用量と状態を表示", "general.platform": "プラットフォーム", "general.platformDetail": "現在の実行環境",
	"thinking.off": "オフ", "thinking.minimal": "最小", "thinking.low": "低", "thinking.medium": "中", "thinking.high": "高", "thinking.xhigh": "非常に高い", "thinking.max": "最大", "thinking.ultra": "ウルトラ", "thinking.title": "推論の強度", "thinking.unsupported": "未対応", "thinking.help": "各レベルの説明", "thinking.faster": "より速く", "thinking.smarter": "より深く", "thinking.detail.off": "推論せずに直接回答します。最速です。", "thinking.detail.minimal": "必要最低限の推論だけを行います。", "thinking.detail.low": "簡単なタスクに適しています。", "thinking.detail.medium": "日常的なコーディングの標準レベルです。", "thinking.detail.high": "複雑なリファクタリングや難しい調査向けです。", "thinking.detail.xhigh": "より深い論理分析を行います。", "thinking.detail.max": "予算をすべて使います。遅くなりますが、より丁寧です。", "thinking.detail.ultra": "利用可能な計算資源をすべて使う最大推論モードです。", "thinking.currentOnly": "現在の会話だけに適用", "thinking.newDefault": "新しい会話の標準レベル", "thinking.providerSupport": "利用できる推論レベルはプロバイダーごとに異なります。「オフ」は常に推論を明示的に無効にします。", "thinking.disabledDetail": "推論はオフです。モデルメニューから再度有効にできます。", "thinking.unsupportedDetail": "このモデルは推論に対応していないため、この設定は反映されません。", "retry.none": "再試行しない", "retry.count": "{count} 回",
	"sidebar.projects": "プロジェクト", "sidebar.chats": "会話", "sidebar.sections": "サイドバーの区分", "sidebar.newChat": "新しい会話", "sidebar.search": "会話を検索", "sidebar.searchPlaceholder": "会話を検索…", "sidebar.notifications": "通知", "sidebar.noMatches": "一致する会話はありません", "sidebar.noArchived": "アーカイブ済みの会話はありません", "sidebar.archiveHint": "会話にポインターを合わせ、アーカイブアイコンを選択してください", "sidebar.noSessions": "会話はまだありません。", "sidebar.newChatHint": "「新しい会話」を選んで始めましょう。", "sidebar.pullRequests": "プルリクエスト", "sidebar.scheduled": "予約済み", "sidebar.plugins": "プラグイン", "sidebar.listSettings": "一覧設定", "sidebar.sortBy": "並び順", "sidebar.updated": "最近更新", "sidebar.created": "最近作成", "sidebar.expandProjects": "すべてのプロジェクトを開く", "sidebar.collapseProjects": "すべてのプロジェクトを閉じる", "sidebar.exitArchive": "アーカイブを終了", "sidebar.archivedCount": "アーカイブ済みの会話（{count}）", "sidebar.archived": "アーカイブ済みの会話",
	"composer.message": "メッセージ", "composer.placeholder": "メッセージを入力、/ でコマンド、@ で参照", "composer.send": "送信", "composer.stop": "停止", "composer.selectProject": "プロジェクトを選択", "composer.selectModel": "モデルを選択", "composer.addAttachment": "ファイルまたは画像を追加", "composer.screenshot": "スクリーンショット", "composer.permissionAsk": "承認を求める", "composer.permissionAuto": "自動承認", "composer.permissionFull": "フルアクセス", "composer.thinking": "推論強度：{level}", "composer.switchingBranch": "ブランチを切り替えています…", "composer.textAttachment": "テキスト / コード添付", "composer.filenameOnly": "ファイル名のみ", "composer.queueLabel": "順番待ちのメッセージ", "composer.queueWaiting": "このターンが終わったら送信します", "composer.queueSteer": "実行を止めずに今すぐ送信", "composer.queueRemove": "削除", "composer.queueMore": "その他", "composer.queueEdit": "メッセージを編集", "composer.queueSideChat": "サイドチャットで開く", "composer.queueReorder": "ドラッグで並べ替え、↑↓ でも可", "composer.queueHeld": "このターンは停止しました。今すぐ送るか、もう一言で列が動きます",
	"empty.chat": "何について話しますか？", "empty.projectQuestion": "{project} で何を作りますか？", "empty.noProject": "プロジェクト未選択", "empty.explore": "コードを調べて理解する", "empty.explorePrompt": "このプロジェクトの全体構成を整理してください。エントリーポイント、主要モジュール、データの流れを含めてください。", "empty.build": "新しい機能、アプリ、ツールを作る", "empty.buildPrompt": "機能を追加したいです。まず変更が必要なファイルを確認し、その後に実装案を提示してください。", "empty.review": "コードをレビューして変更を提案する", "empty.reviewPrompt": "現在のワークスペースにある未コミットの変更をレビューし、欠陥とリスクを深刻度順に示してください。", "empty.fix": "問題や失敗を修正する", "empty.fixPrompt": "問題の根本原因を特定してください。再現し、場所を絞り込み、最小限で完全な修正を行ってください。",
	"command.builtin": "コマンド", "command.custom": "カスタムコマンド", "command.skills": "スキル", "command.slash": "スラッシュコマンド",
	"permission.mode": "権限モード", "permission.question": "Lyra の操作をどのように承認しますか？", "permission.askDetail": "ファイルの編集やネットワークアクセスの前に常に確認する", "permission.autoDetail": "危険と判断された操作だけ承認を求める", "permission.fullDetail": "ネットワークとこのコンピューター上のすべてのファイルへ無制限にアクセスする", "permission.confirmTitle": "フルアクセスを有効にしますか？", "permission.confirmSummary": "Lyra は操作ごとの承認を求めず、直接実行します。", "permission.files": "ファイルとフォルダー", "permission.filesDetail": "現在のプロジェクト外も含め、このコンピューター上のファイルを読み書き、アップロード、削除します。", "permission.terminal": "ターミナルと Git", "permission.terminalDetail": "コマンドの実行、ソフトウェアのインストール、システム設定と Git 履歴の変更を行います。", "permission.network": "ネットワークとプラグイン", "permission.networkDetail": "ネットワークへアクセスし、データを送信して接続済みツールを呼び出します。", "permission.risk": "データの損失や漏えいにつながる可能性があります。いつでも自動承認へ戻せます。", "permission.confirmEnable": "フルアクセスを有効にする",
	"project.switch": "プロジェクトを切り替える", "project.search": "プロジェクトを検索", "project.new": "新しいプロジェクト", "project.without": "プロジェクトなしで作業", "project.none": "プロジェクトはまだありません", "model.unavailable": "モデルを利用できません",
	"sidebar.manual": "手動順序",
	"general.autoSummarizeTitle": "会話タイトルの自動要約",
	"general.autoSummarizeTitleDetail": "長いメッセージのタイトルを短くします。優先的に @fast を使い、トークンを消費します。",
} satisfies MessageCatalog;
