import type { MessageCatalog } from "./zh-CN.ts";

export const ko = {
	"common.cancel": "취소", "common.confirm": "확인", "common.delete": "삭제", "common.hide": "숨기기", "common.loading": "여는 중", "common.save": "저장", "common.show": "표시",
	"app.backWorkspace": "작업 공간으로 돌아가기", "app.guide": "안내", "app.hideSettingsNavigation": "설정 탐색 숨기기 {shortcut}", "app.mainProcessError": "메인 프로세스 오류", "app.panel": "패널", "app.plugins": "플러그인", "app.pullRequests": "Pull Request", "app.scheduledTasks": "예약 작업", "app.settingsNavigation": "설정 탐색", "app.showSettingsNavigation": "설정 탐색 표시 {shortcut}", "app.sidebar": "사이드바",
	"language.title": "인터페이스 언어", "language.detail": "Lyra의 메뉴, 설정, 작업 안내 언어를 변경합니다. 대화 내용, 코드, 터미널 출력은 원문을 유지합니다.", "language.system": "시스템 언어 사용", "language.systemDetected": "현재 시스템 언어", "language.zh-CN": "简体中文", "language.zh-TW": "繁體中文", "language.en": "English", "language.fr": "Français", "language.ru": "Русский", "language.ko": "한국어", "language.ja": "日本語",
	"settings.group.basic": "기본 설정", "settings.group.agent": "에이전트 기능", "settings.group.data": "데이터 및 사용량", "settings.group.vcs": "코드 및 버전 관리", "settings.group.about": "정보 및 보관", "settings.general": "일반", "settings.appearance": "모양", "settings.formatting": "코드 서식", "settings.personalization": "개인 설정", "settings.models": "모델", "settings.forges": "코드 호스팅", "settings.screenshot": "스크린샷", "settings.browser": "브라우저", "settings.extensions": "플러그인", "settings.agents": "하위 에이전트", "settings.delegation": "위임 설정", "settings.commands": "명령", "settings.hooks": "후크", "settings.search": "웹 검색", "settings.access": "접근 권한", "settings.index": "인덱스", "settings.sync": "모바일 동기화", "settings.usage": "사용량", "settings.worktrees": "Worktrees", "settings.about": "정보", "settings.archived": "보관된 대화",
	"general.permissions": "권한", "general.defaultPermission": "기본 접근 권한", "general.defaultPermissionDetail": "Lyra는 현재 작업 공간의 파일을 항상 읽고 편집할 수 있습니다. 필요한 경우 추가 권한을 요청합니다.", "general.alwaysEnabled": "항상 사용", "general.autoReview": "자동 검토", "general.autoReviewDetail": "git status, ls, grep 같은 읽기 전용 명령은 자동으로 허용됩니다. 쓰기 및 알 수 없는 명령은 계속 승인이 필요합니다.", "general.fullAccess": "전체 접근", "general.fullAccessDetail": "Lyra가 승인 없이 파일을 편집하고 명령을 실행하며 네트워크에 접근할 수 있습니다. 데이터 손실이나 의도하지 않은 작업의 위험이 크게 높아집니다.", "general.section": "일반", "general.fileTarget": "기본 파일 열기 앱", "general.fileTargetDetail": "파일 경로를 클릭할 때 사용할 앱을 선택합니다", "general.thinking": "기본 추론 강도", "general.thinkingDetail": "새 대화의 추론 예산입니다. 각 대화에서 입력창 오른쪽의 설정으로 따로 변경할 수 있습니다.", "general.retry": "요청 재시도", "general.retryDetail": "네트워크 오류 후 모델 요청을 시도할 횟수이며 첫 시도를 포함합니다. 출력이 시작된 답변은 다시 시도하지 않습니다.", "general.bottomPanel": "하단 패널", "general.bottomPanelDetail": "대화 아래에 사용량과 상태 표시", "general.platform": "플랫폼", "general.platformDetail": "현재 실행 환경",
	"thinking.off": "끔", "thinking.minimal": "최소", "thinking.low": "낮음", "thinking.medium": "중간", "thinking.high": "높음", "thinking.xhigh": "매우 높음", "thinking.max": "최대", "thinking.ultra": "울트라", "thinking.title": "추론 강도", "thinking.unsupported": "지원 안 함", "thinking.help": "단계별 설명", "thinking.faster": "더 빠르게", "thinking.smarter": "더 깊게", "thinking.detail.off": "추론 없이 바로 답합니다. 가장 빠릅니다.", "thinking.detail.minimal": "최소한의 추론만 사용합니다.", "thinking.detail.low": "간단한 작업에 적합합니다.", "thinking.detail.medium": "일상적인 코딩의 기본 단계입니다.", "thinking.detail.high": "복잡한 리팩터링과 어려운 문제 해결에 적합합니다.", "thinking.detail.xhigh": "더 깊은 논리 분석을 사용합니다.", "thinking.detail.max": "전체 예산을 사용합니다. 느리지만 더 철저합니다.", "thinking.detail.ultra": "가용 연산을 모두 사용하는 최고 추론 단계입니다.", "thinking.currentOnly": "현재 대화에만 적용", "thinking.newDefault": "새 대화의 기본 단계", "thinking.providerSupport": "공급자마다 지원하는 추론 단계가 다릅니다. 끔은 항상 추론을 명시적으로 비활성화합니다.", "thinking.disabledDetail": "추론이 꺼져 있습니다. 모델 메뉴에서 다시 켤 수 있습니다.", "thinking.unsupportedDetail": "현재 모델은 추론을 지원하지 않아 이 설정이 적용되지 않습니다.", "retry.none": "재시도 안 함", "retry.count": "{count}회 시도",
	"sidebar.projects": "프로젝트", "sidebar.chats": "대화", "sidebar.sections": "사이드바 구역", "sidebar.newChat": "새 대화", "sidebar.search": "대화 검색", "sidebar.searchPlaceholder": "대화 검색…", "sidebar.notifications": "알림", "sidebar.noMatches": "일치하는 대화가 없습니다", "sidebar.noArchived": "보관된 대화가 없습니다", "sidebar.archiveHint": "대화에 마우스를 올리고 보관 아이콘을 선택하세요", "sidebar.noSessions": "아직 대화가 없습니다.", "sidebar.newChatHint": "새 대화를 선택해 시작하세요.", "sidebar.pullRequests": "Pull Request", "sidebar.scheduled": "예약됨", "sidebar.plugins": "플러그인", "sidebar.listSettings": "목록 설정", "sidebar.sortBy": "정렬 기준", "sidebar.updated": "최근 업데이트", "sidebar.created": "최근 생성", "sidebar.expandProjects": "모든 프로젝트 펼치기", "sidebar.collapseProjects": "모든 프로젝트 접기", "sidebar.exitArchive": "보관함 나가기", "sidebar.archivedCount": "보관된 대화 ({count})", "sidebar.archived": "보관된 대화",
	"composer.message": "메시지", "composer.placeholder": "메시지 입력, / 명령, @ 참조", "composer.send": "보내기", "composer.stop": "중지", "composer.selectProject": "프로젝트 선택", "composer.selectModel": "모델 선택", "composer.addAttachment": "파일 또는 이미지 추가", "composer.screenshot": "스크린샷", "composer.permissionAsk": "승인 요청", "composer.permissionAuto": "자동 승인", "composer.permissionFull": "전체 접근", "composer.thinking": "추론 강도: {level}", "composer.switchingBranch": "브랜치 전환 중…", "composer.textAttachment": "텍스트 / 코드 첨부", "composer.filenameOnly": "파일 이름만",
	"empty.chat": "무엇을 이야기할까요?", "empty.projectQuestion": "{project}에서 무엇을 만들까요?", "empty.noProject": "선택한 프로젝트 없음", "empty.explore": "코드 탐색 및 이해", "empty.explorePrompt": "이 프로젝트의 전체 구조를 설명해 주세요. 진입점, 핵심 모듈, 데이터 흐름을 포함해 주세요.", "empty.build": "새 기능, 앱 또는 도구 만들기", "empty.buildPrompt": "기능을 추가하려고 합니다. 먼저 수정해야 할 파일을 확인한 다음 구현 방안을 제안해 주세요.", "empty.review": "코드 검토 및 변경 제안", "empty.reviewPrompt": "현재 작업 공간의 커밋되지 않은 변경을 검토하고 결함과 위험을 심각도 순으로 알려 주세요.", "empty.fix": "문제와 실패 수정", "empty.fixPrompt": "문제의 근본 원인을 찾아 주세요. 재현하고 위치를 확인한 다음 가장 작은 완전한 수정안을 적용해 주세요.",
	"command.builtin": "명령", "command.custom": "사용자 명령", "command.skills": "스킬", "command.slash": "슬래시 명령",
	"permission.mode": "권한 모드", "permission.question": "Lyra 작업을 어떻게 승인할까요?", "permission.askDetail": "파일을 편집하거나 네트워크에 접근하기 전에 항상 묻기", "permission.autoDetail": "위험하다고 감지된 작업만 승인 요청", "permission.fullDetail": "이 컴퓨터의 네트워크와 모든 파일에 제한 없이 접근", "permission.confirmTitle": "전체 접근을 켤까요?", "permission.confirmSummary": "Lyra가 각 작업의 승인을 묻지 않고 바로 실행합니다.", "permission.files": "파일 및 폴더", "permission.filesDetail": "현재 프로젝트 밖을 포함해 이 컴퓨터의 파일을 읽고, 쓰고, 업로드하거나 삭제합니다.", "permission.terminal": "터미널 및 Git", "permission.terminalDetail": "명령 실행, 소프트웨어 설치, 시스템 설정 및 Git 기록 변경을 수행합니다.", "permission.network": "네트워크 및 플러그인", "permission.networkDetail": "네트워크에 접근하고 데이터를 보내며 연결된 도구를 호출합니다.", "permission.risk": "데이터 손실이나 유출이 발생할 수 있습니다. 언제든 자동 승인으로 돌아갈 수 있습니다.", "permission.confirmEnable": "전체 접근 켜기",
	"project.switch": "프로젝트 전환", "project.search": "프로젝트 검색", "project.new": "새 프로젝트", "project.without": "프로젝트 없이 작업", "project.none": "아직 프로젝트가 없습니다", "model.unavailable": "모델을 사용할 수 없음",
	"sidebar.manual": "수동 정렬",
	"general.autoSummarizeTitle": "대화 제목 자동 요약",
	"general.autoSummarizeTitleDetail": "긴 메시지 제목을 줄입니다. @fast를 우선 사용하며 모델 토큰이 소모됩니다.",
} satisfies MessageCatalog;
