import type { MessageCatalog } from "./zh-CN.ts";

export const ru = {
	"common.cancel": "Отмена", "common.confirm": "Подтвердить", "common.delete": "Удалить", "common.hide": "Скрыть", "common.loading": "Открытие", "common.save": "Сохранить", "common.show": "Показать",
	"app.backWorkspace": "Вернуться в рабочую область", "app.guide": "Настройка", "app.hideSettingsNavigation": "Скрыть навигацию настроек {shortcut}", "app.mainProcessError": "Ошибка основного процесса", "app.panel": "Панели", "app.plugins": "Плагины", "app.pullRequests": "Запросы на слияние", "app.scheduledTasks": "Запланированные задачи", "app.settingsNavigation": "Навигация настроек", "app.showSettingsNavigation": "Показать навигацию настроек {shortcut}", "app.sidebar": "Боковая панель",
	"language.title": "Язык интерфейса", "language.detail": "Меняет язык меню, настроек и подсказок Lyra. Текст бесед, код и вывод терминала остаются без перевода.", "language.system": "Как в системе", "language.systemDetected": "Текущий язык системы", "language.zh-CN": "简体中文", "language.zh-TW": "繁體中文", "language.en": "English", "language.fr": "Français", "language.ru": "Русский", "language.ko": "한국어", "language.ja": "日本語",
	"settings.group.basic": "Основные настройки", "settings.group.agent": "Возможности агента", "settings.group.data": "Данные и статистика", "settings.group.vcs": "Код и версии", "settings.group.about": "О приложении и архив", "settings.general": "Общие", "settings.appearance": "Оформление", "settings.formatting": "Форматирование кода", "settings.personalization": "Персонализация", "settings.models": "Модели", "settings.forges": "Хостинг кода", "settings.screenshot": "Снимки экрана", "settings.browser": "Браузер", "settings.extensions": "Плагины", "settings.agents": "Субагенты", "settings.delegation": "Делегирование", "settings.commands": "Команды", "settings.hooks": "Хуки", "settings.search": "Поиск в интернете", "settings.access": "Доступ", "settings.index": "Индекс", "settings.sync": "Синхронизация с телефоном", "settings.usage": "Статистика использования", "settings.worktrees": "Worktrees", "settings.about": "О приложении", "settings.archived": "Архив бесед",
	"general.permissions": "Разрешения", "general.defaultPermission": "Доступ по умолчанию", "general.defaultPermissionDetail": "Lyra всегда может читать и изменять файлы в текущей рабочей области. При необходимости запрашивается дополнительный доступ.", "general.alwaysEnabled": "Всегда включено", "general.autoReview": "Автоматическая проверка", "general.autoReviewDetail": "Команды только для чтения, например git status, ls и grep, выполняются автоматически. Запись и неизвестные команды по-прежнему требуют подтверждения.", "general.fullAccess": "Полный доступ", "general.fullAccessDetail": "Lyra сможет изменять файлы, выполнять команды и обращаться к сети без подтверждения. Это заметно повышает риск потери данных и непреднамеренных действий.", "general.section": "Общие", "general.fileTarget": "Приложение для открытия файлов", "general.fileTargetDetail": "Выберите приложение, которое откроет файл при нажатии на путь", "general.thinking": "Стандартная глубина рассуждений", "general.thinkingDetail": "Бюджет рассуждений для новых бесед. Для каждой беседы его можно изменить в поле ввода.", "general.retry": "Повторные запросы", "general.retryDetail": "Число попыток запроса модели после сетевой ошибки, включая первую. Уже начатый ответ повторно не запускается.", "general.bottomPanel": "Нижняя панель", "general.bottomPanelDetail": "Показывать расход и состояние под беседой", "general.platform": "Платформа", "general.platformDetail": "Текущая среда выполнения",
	"thinking.off": "Выкл.", "thinking.minimal": "Минимум", "thinking.low": "Низкая", "thinking.medium": "Средняя", "thinking.high": "Высокая", "thinking.xhigh": "Очень высокая", "thinking.max": "Максимум", "thinking.ultra": "Ультра", "thinking.title": "Глубина рассуждений", "thinking.unsupported": "Не поддерживается", "thinking.help": "Описание уровней", "thinking.faster": "Быстрее", "thinking.smarter": "Глубже", "thinking.detail.off": "Ответ без рассуждений. Самый быстрый режим.", "thinking.detail.minimal": "Использовать минимум рассуждений.", "thinking.detail.low": "Подходит для простых задач.", "thinking.detail.medium": "Стандартный уровень для повседневной разработки.", "thinking.detail.high": "Для сложного рефакторинга и трудной диагностики.", "thinking.detail.xhigh": "Более глубокий логический анализ.", "thinking.detail.max": "Использовать весь бюджет. Медленнее, но тщательнее.", "thinking.detail.ultra": "Максимальная глубина с полной вычислительной мощностью.", "thinking.currentOnly": "Только для этого чата", "thinking.newDefault": "По умолчанию для новых чатов", "thinking.providerSupport": "Набор уровней зависит от поставщика. Режим «Выкл.» всегда явно отключает рассуждения.", "thinking.disabledDetail": "Рассуждения отключены. Их можно включить в меню модели.", "thinking.unsupportedDetail": "Эта модель не поддерживает рассуждения, настройка не действует.", "retry.none": "Без повторов", "retry.count": "Попыток: {count}",
	"sidebar.projects": "Проекты", "sidebar.chats": "Беседы", "sidebar.sections": "Разделы боковой панели", "sidebar.newChat": "Новая беседа", "sidebar.search": "Поиск бесед", "sidebar.searchPlaceholder": "Поиск бесед…", "sidebar.notifications": "Уведомления", "sidebar.noMatches": "Подходящих бесед нет", "sidebar.noArchived": "Архивных бесед нет", "sidebar.archiveHint": "Наведите указатель на беседу и выберите значок архива", "sidebar.noSessions": "Бесед пока нет.", "sidebar.newChatHint": "Выберите «Новая беседа», чтобы начать.", "sidebar.pullRequests": "Запросы на слияние", "sidebar.scheduled": "Запланировано", "sidebar.plugins": "Плагины", "sidebar.listSettings": "Настройки списка", "sidebar.sortBy": "Сортировка", "sidebar.updated": "Недавно обновлённые", "sidebar.created": "Недавно созданные", "sidebar.expandProjects": "Развернуть все проекты", "sidebar.collapseProjects": "Свернуть все проекты", "sidebar.exitArchive": "Выйти из архива", "sidebar.archivedCount": "Архивные беседы ({count})", "sidebar.archived": "Архивные беседы",
	"composer.message": "Сообщение", "composer.placeholder": "Сообщение, / для команд, @ для ссылок", "composer.send": "Отправить", "composer.stop": "Остановить", "composer.selectProject": "Выбрать проект", "composer.selectModel": "Выбрать модель", "composer.addAttachment": "Добавить файл или изображение", "composer.screenshot": "Снимок экрана", "composer.permissionAsk": "Запрашивать доступ", "composer.permissionAuto": "Автоподтверждение", "composer.permissionFull": "Полный доступ", "composer.thinking": "Глубина рассуждений: {level}", "composer.switchingBranch": "Переключение ветки…", "composer.textAttachment": "Текстовый файл / код", "composer.filenameOnly": "Только имя файла", "composer.queueLabel": "Сообщения в очереди", "composer.queueWaiting": "Отправится после этого хода", "composer.queueSteer": "Отправить сейчас, не прерывая текущий ход", "composer.queueRemove": "Удалить", "composer.queueMore": "Ещё", "composer.queueEdit": "Изменить сообщение", "composer.queueSideChat": "Открыть в боковом чате", "composer.queueReorder": "Перетащите для порядка или ↑↓", "composer.queueHeld": "Ход остановлен: отправьте сейчас или напишите ещё, чтобы сдвинуть очередь",
	"empty.chat": "О чём вы хотите поговорить?", "empty.projectQuestion": "Что вы хотите создать в {project}?", "empty.noProject": "Проект не выбран", "empty.explore": "Изучить и понять код", "empty.explorePrompt": "Объясни архитектуру проекта: точки входа, основные модули и поток данных.", "empty.build": "Создать функцию, приложение или инструмент", "empty.buildPrompt": "Я хочу добавить функцию. Сначала найди нужные файлы, затем предложи реализацию.", "empty.review": "Проверить код и предложить изменения", "empty.reviewPrompt": "Проверь незакоммиченные изменения рабочей области. Перечисли ошибки и риски по степени серьёзности.", "empty.fix": "Исправить ошибку или сбой", "empty.fixPrompt": "Найди первопричину проблемы. Воспроизведи её, локализуй и внеси минимальное полное исправление.",
	"command.builtin": "Команды", "command.custom": "Пользовательские команды", "command.skills": "Навыки", "command.slash": "Слэш-команды",
	"permission.mode": "Режим разрешений", "permission.question": "Как Lyra должен подтверждать действия?", "permission.askDetail": "Всегда спрашивать перед изменением файлов или доступом к сети", "permission.autoDetail": "Спрашивать только для действий, которые выглядят рискованными", "permission.fullDetail": "Неограниченный доступ к сети и файлам этого компьютера", "permission.confirmTitle": "Включить полный доступ?", "permission.confirmSummary": "Lyra будет выполнять действия напрямую, без отдельных запросов подтверждения.", "permission.files": "Файлы и папки", "permission.filesDetail": "Чтение, запись, отправка и удаление файлов на компьютере, в том числе вне текущего проекта.", "permission.terminal": "Терминал и Git", "permission.terminalDetail": "Выполнение команд, установка программ, изменение системных настроек и истории Git.", "permission.network": "Сеть и плагины", "permission.networkDetail": "Доступ к сети, отправка данных и вызов подключённых инструментов.", "permission.risk": "Возможна потеря или утечка данных. В любой момент можно вернуться к автоподтверждению.", "permission.confirmEnable": "Включить полный доступ",
	"project.switch": "Сменить проект", "project.search": "Поиск проектов", "project.new": "Новый проект", "project.without": "Работать без проекта", "project.none": "Проектов пока нет", "model.unavailable": "Модель недоступна",
	"sidebar.manual": "Ручной порядок",
	"general.autoSummarizeTitle": "Автоматические заголовки",
	"general.autoSummarizeTitleDetail": "Сокращает длинные заголовки, по возможности с @fast. Расходует токены модели.",
} satisfies MessageCatalog;
