import type { MessageCatalog } from "./zh-CN.ts";

export const zhTW = {
	"common.cancel": "取消", "common.confirm": "確認", "common.delete": "刪除", "common.hide": "隱藏", "common.loading": "正在開啟", "common.save": "儲存", "common.show": "顯示",
	"app.backWorkspace": "返回工作區", "app.guide": "引導", "app.hideSettingsNavigation": "隱藏設定導覽 {shortcut}", "app.mainProcessError": "主程序發生錯誤", "app.panel": "面板", "app.plugins": "外掛", "app.pullRequests": "拉取請求", "app.scheduledTasks": "排程任務", "app.settingsNavigation": "設定導覽", "app.showSettingsNavigation": "顯示設定導覽 {shortcut}", "app.sidebar": "側邊欄",
	"language.title": "介面語言", "language.detail": "切換 Lyra 的選單、設定與操作提示。對話內容、程式碼與終端輸出維持原文。", "language.system": "跟隨系統", "language.systemDetected": "目前系統語言", "language.zh-CN": "简体中文", "language.zh-TW": "繁體中文", "language.en": "English", "language.fr": "Français", "language.ru": "Русский", "language.ko": "한국어", "language.ja": "日本語",
	"settings.group.basic": "基本設定", "settings.group.agent": "Agent 能力", "settings.group.data": "資料與統計", "settings.group.vcs": "程式碼與版本控制", "settings.group.about": "關於與封存", "settings.general": "一般", "settings.appearance": "外觀", "settings.formatting": "程式碼格式化", "settings.personalization": "個人化", "settings.models": "模型設定", "settings.forges": "程式碼託管", "settings.screenshot": "螢幕截圖", "settings.browser": "瀏覽器", "settings.extensions": "外掛", "settings.agents": "子智能體", "settings.delegation": "子智能體調度", "settings.commands": "命令", "settings.hooks": "鉤子", "settings.search": "網頁搜尋", "settings.access": "存取授權", "settings.index": "索引庫", "settings.sync": "行動端同步", "settings.usage": "使用統計", "settings.worktrees": "Worktrees", "settings.about": "關於", "settings.archived": "已封存的聊天",
	"general.permissions": "權限", "general.defaultPermission": "預設權限", "general.defaultPermissionDetail": "Lyra 一律可以讀取與編輯目前工作區內的檔案，需要時會要求額外權限。", "general.alwaysEnabled": "永遠開啟", "general.autoReview": "自動審核", "general.autoReviewDetail": "唯讀命令（git status、ls、grep 等）自動放行，寫入與未知命令仍需核准。", "general.fullAccess": "完整存取權限", "general.fullAccessDetail": "開啟後，Lyra 無需核准即可修改檔案、執行命令與存取網路，資料遺失或非預期行為的風險會顯著提高。", "general.section": "一般", "general.fileTarget": "預設檔案開啟目標", "general.fileTargetDetail": "點擊檔案路徑時要使用哪個應用程式", "general.thinking": "預設推理強度", "general.thinkingDetail": "新對話使用的思考預算，每個對話都能在輸入框右側單獨調整。", "general.retry": "要求重試次數", "general.retryDetail": "模型要求因網路中斷失敗時的嘗試次數，包含首次。已開始輸出的回答不會重試。", "general.bottomPanel": "底部面板", "general.bottomPanelDetail": "在對話底部顯示用量與狀態資訊", "general.platform": "平台", "general.platformDetail": "目前執行環境",
	"thinking.off": "關", "thinking.minimal": "極簡", "thinking.low": "低", "thinking.medium": "中", "thinking.high": "高", "thinking.xhigh": "超高", "thinking.max": "最高", "thinking.ultra": "極致", "thinking.title": "推理強度", "thinking.unsupported": "不支援", "thinking.help": "各檔位說明", "thinking.faster": "更快", "thinking.smarter": "更聰明", "thinking.detail.off": "不推理，直接作答，速度最快。", "thinking.detail.minimal": "只進行最低限度的思考。", "thinking.detail.low": "適合簡單任務。", "thinking.detail.medium": "日常程式開發的預設檔位。", "thinking.detail.high": "適合複雜重構與疑難排查。", "thinking.detail.xhigh": "進行更深層的邏輯推演。", "thinking.detail.max": "使用最高預算，速度最慢但更穩定。", "thinking.detail.ultra": "極致推理模式，使用全部算力。", "thinking.currentOnly": "只套用到目前對話", "thinking.newDefault": "作為新對話的預設檔位", "thinking.providerSupport": "各供應商支援的推理檔位不同；「關」一律明確要求不要推理。", "thinking.disabledDetail": "推理已關閉，可在模型選單中重新開啟。", "thinking.unsupportedDetail": "目前模型不支援推理，此設定不會生效。", "retry.none": "不重試", "retry.count": "{count} 次",
	"sidebar.projects": "專案", "sidebar.chats": "聊天", "sidebar.sections": "側邊欄分區", "sidebar.newChat": "新對話", "sidebar.search": "搜尋對話", "sidebar.searchPlaceholder": "搜尋對話…", "sidebar.notifications": "通知", "sidebar.noMatches": "沒有符合的對話", "sidebar.noArchived": "還沒有封存的聊天", "sidebar.archiveHint": "將滑鼠移到對話上，再點擊封存圖示", "sidebar.noSessions": "還沒有對話。", "sidebar.newChatHint": "點擊「新對話」開始。", "sidebar.pullRequests": "拉取請求", "sidebar.scheduled": "已排程", "sidebar.plugins": "外掛", "sidebar.listSettings": "清單設定", "sidebar.sortBy": "排序方式", "sidebar.updated": "最近更新", "sidebar.created": "最近建立", "sidebar.expandProjects": "展開所有專案", "sidebar.collapseProjects": "收合所有專案", "sidebar.exitArchive": "離開封存", "sidebar.archivedCount": "已封存的聊天（{count}）", "sidebar.archived": "已封存的聊天",
	"composer.message": "訊息", "composer.placeholder": "輸入訊息，/ 指令，@ 引用", "composer.send": "傳送", "composer.stop": "停止", "composer.selectProject": "選擇專案", "composer.selectModel": "選擇模型", "composer.addAttachment": "加入檔案或圖片", "composer.screenshot": "螢幕截圖", "composer.permissionAsk": "要求核准", "composer.permissionAuto": "自動核准", "composer.permissionFull": "完整存取", "composer.thinking": "推理強度：{level}", "composer.switchingBranch": "正在切換分支…", "composer.textAttachment": "文字 / 程式碼附件", "composer.filenameOnly": "僅檔名",
	"empty.chat": "想聊點什麼？", "empty.projectQuestion": "想在 {project} 裡開發什麼？", "empty.noProject": "尚未選擇專案", "empty.explore": "探索並理解程式碼", "empty.explorePrompt": "幫我梳理這個專案的整體架構：入口在哪裡、核心模組如何劃分、資料如何流動。", "empty.build": "建構新功能、應用程式或工具", "empty.buildPrompt": "我想新增一項功能，請先確認現有程式碼中需要修改哪些檔案，再提出實作方案。", "empty.review": "審查程式碼並提出修改建議", "empty.reviewPrompt": "審查目前工作區尚未提交的變更，指出缺陷與風險，並依嚴重程度排序。", "empty.fix": "修復問題與失敗", "empty.fixPrompt": "幫我找出問題根因。先重現，再定位，最後以最小完整改動修復。",
	"command.builtin": "命令", "command.custom": "自訂命令", "command.skills": "技能", "command.slash": "斜線命令",
	"permission.mode": "權限模式", "permission.question": "應如何核准 Lyra 的操作？", "permission.askDetail": "編輯檔案與存取網路時一律詢問", "permission.autoDetail": "只對偵測到的風險操作要求核准", "permission.fullDetail": "可不受限制地存取網路與此電腦上的所有檔案", "permission.confirmTitle": "開啟完整存取權限？", "permission.confirmSummary": "Lyra 將直接執行操作，不再逐項要求核准。", "permission.files": "檔案與資料夾", "permission.filesDetail": "讀寫、上傳或刪除此電腦上的檔案，不限於目前專案。", "permission.terminal": "終端與 Git", "permission.terminalDetail": "執行命令、安裝軟體、變更系統設定與 Git 歷史。", "permission.network": "網路與外掛", "permission.networkDetail": "存取網路、傳送資料及呼叫已連接的工具。", "permission.risk": "可能造成資料遺失或外洩，可隨時切回「自動核准」。", "permission.confirmEnable": "確認開啟",
	"project.switch": "切換專案", "project.search": "搜尋專案", "project.new": "新增專案", "project.without": "不在專案中工作", "project.none": "還沒有專案", "model.unavailable": "模型無法使用",
	"sidebar.manual": "手動排序",
	"general.autoSummarizeTitle": "智慧標題摘要",
	"general.autoSummarizeTitleDetail": "自動精簡長訊息標題，優先使用 @fast，會產生模型用量。",
} satisfies MessageCatalog;
